Porthos/Orkidea.Porthos.FrontEnd/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Orkidea.Porthos.FrontEnd.Controllers
{
    public class ProjectController : Controller
    {
        //
        // GET: /Project/

        public ActionResult Index()
        {
            ViewBag.menu = "Proyectos";
            ViewBag.h1 = "Proyectos";
            ViewBag.h2 = "Registre aquí los diferentes proyectos a manejar por Porthos";
            ViewBag.breadcrumb = "<a href = '../Home/index'>Inicio</a>|Proyectos";
            ViewBag.icon = "fa fa-building";
            return View();
        }        
    }
}

Porthos/Orkidea.Porthos.FrontEnd/Controllers/SecurityController.cs
using System;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Orkidea.Porthos.Business;
using Orkidea.Porthos.Entities;
using Orkidea.Porthos.Security;
using Orkidea.Porthos.Utilities;

namespace Orkidea.Porthos.FrontEnd.Controllers
{
    public class SecurityController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(People user, string returnUrl)
        {
            Cryptography oCrypto = new Cryptography();
            if (!String.IsNullOrEmpty(user.usuario) && !String.IsNullOrEmpty(user.contraseña))
            {
                user.contraseña = oCrypto.Encrypt(user.contraseña);

                PeopleBiz peopleBiz = new PeopleBiz();

                People usuarioAutenticado = peopleBiz.PeopleAuthentication(user);

                if (usuarioAutenticado.id != null)
                {
                    FormsAuthentication.SetAuthCookie(user.usuario, false);

                    string userData = usuarioAutenticado.id.ToString().Trim() + "|" + StringHelper.NombreUsuario(usuarioAutenticado) + "|" + (usuarioAutenticado.usuarioOrkidea ? "true" : "false");

                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, user.usuario, DateTime.Now, DateTime.Now.AddMinutes(150), false, userData);

                    string encTicket = FormsAuthentication.Encrypt(ticket);
                    HttpCookie faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
                    HttpContext.Response.Cookies.Add(faCookie);

                    HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];

                    if (authCookie != null)
                    {
                        FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
                        CustomIdentity identity = new CustomIdentity(authTicket.Name, userData);
                        GenericPrincipal newUser = new GenericPrincipal(identity, new string[] { });
                        HttpContext.User = newUser;
                    }

                    return RedirectToLocal(returnUrl);
                }
            }

            return View(user);
        }

        [Authorize]
        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                //return RedirectToAction("Index", "Home");
                return RedirectToAction
                ("Login");
            }
        }

    }
}

Porthos/Orkidea.Porthos.FrontEnd/Views/Shared/Copy of _Layout.cshtml
<!DOCTYPE html>
<html lang="es-co" data-ng-app="">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>
        <script src="https://code.angularjs.org/1.2.16/angular.min.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Porthos/Orkidea.Porthos.FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-co">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.h1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet">

    <!-- Loading Stylesheets -->
    <link href="@Url.Content("~/css/font-awesome.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/style.css")" rel="stylesheet" type="text/css">

    <!-- Loading Custom Stylesheets -->
    <link href="@Url.Content("~/css/custom.css")" rel="stylesheet">

    <link rel="shortcut icon" href="@Url.Content("~/images/favicon.ico")">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="@Url.Content("~/js/html5shiv.js")"></script>
      <![endif]-->

    @{
        System.Security.Principal.IIdentity context = Context.User.Identity;
        int user = 0;
        string userName = "";
        string longName = "";
        bool admin = false;

        if (context.IsAuthenticated)
        {
            System.Web.Security.FormsIdentity ci = (System.Web.Security.FormsIdentity)Context.User.Identity;
            string[] userData = ci.Ticket.UserData.Split('|');

            user = int.Parse(userData[0]);
            userName = ci.Name;
            longName = userData[1];
            admin = bool.Parse(userData[2]);
        }


        string[] breadcrumb = ((string)ViewBag.breadcrumb).Split('|');

            
    }
</head>
<body>
    <div class="site-holder">
        <!-- this is a dummy text -->
        <!-- .navbar -->
        <nav class="navbar" role="navigation">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><i class="fa fa-list btn-nav-toggle-responsive text-white"></i>
                    <span class="logo">
                        <img src="@Url.Content("~/Images/Porthos_GH_logo_blanco.png")" /></span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav user-menu navbar-right ">

                    <li><a href="#" class="user dropdown-toggle" data-toggle="dropdown"><span class="username">
                        <img src="images/profiles/eleven.png" class="user-avatar" alt="">
                        @longName </span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-user"></i>My Profile</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i>Inbox</a></li>
                            <li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Logout", "Security")" class="text-danger"><i class="fa fa-lock"></i>Logout</a></li>
                        </ul>
                        <li><a href="#" class="settings dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="badge bg-pink">1</span></a>
                            <ul class="dropdown-menu inbox">
                                <li>
                                    <a href="inbox.php">
                                        <img src="images/profiles/three.png" alt="" class="avatar">
                                        <div class="message">
                                            <span class="username">John Deo</span>
                                            <span class="mini-details">(6) <i class="fa fa-paper-clip"></i></span>
                                            <span class="time pull-right"><i class="fa fa-clock-o"></i>06:58 PM</span>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ... </p>
                                        </div>
                                    </a>
                                </li>
                                <li><a href="inbox.php" class="btn bg-primary">View All</a></li>
                            </ul>
                        </li>
                    <li><a href="#" class="settings dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell animated shake"></i><span class="badge bg-success">1</span></a>
                        <ul class="dropdown-menu notifications">
                            <li>
                                <a href="#">
                                    <i class="fa fa-user noty-icon bg-primary"></i>
                                    <span class="description">10 Users are registered</span>
                                    <span class="time"><i class="fa fa-clock-o"></i>06:58 PM</span>
                                </a>
                            </li>
                            <li><a href="#" class="btn bg-primary">View All</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <!-- /.navbar -->

        <!-- .box-holder -->
        <div class="box-holder">

            <!-- .left-sidebar -->
            <div class="left-sidebar">
                <div class="sidebar-holder">
                    <ul class="nav  nav-list">

                        <!-- sidebar to mini Sidebar toggle -->
                        <li class="nav-toggle">
                            <button class="btn  btn-nav-toggle text-primary"><i class="fa fa-angle-double-left toggle-left"></i></button>
                        </li>

                        @if (ViewBag.menu == "Home")
                        {
                            <li class="active"><a href="@Url.Action("Index", "Home")" data-original-title="Dashboard"><i class="fa fa-dashboard"></i><span class="hidden-minibar">Dashboard </span></a></li>                            
                        }
                        else
                        {
                            <li><a href="@Url.Action("Index", "Home")" data-original-title="Dashboard"><i class="fa fa-dashboard"></i><span class="hidden-minibar">Dashboard </span></a></li>
                        }
                        @if (ViewBag.menu == "Proyectos")
                        {
                            <li class="active"><a href="@Url.Action("Index", "Project")" data-original-title="Dashboard"><i class="fa fa-building"></i><span class="hidden-minibar">Proyectos </span></a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Index", "Project")" data-original-title="Dashboard"><i class="fa fa-building"></i><span class="hidden-minibar">Proyectos </span></a></li>
                        }

                        @*<li><a href="top-navbar.html" data-original-title="Top Navbar"><i class="fa fa-indent"></i><span class="hidden-minibar">Top Navbar </span></a></li>



                        <li>
                            <a class="dropdown" href="#" data-original-title="Pages"><i class="fa fa-book"></i><span class="hidden-minibar">Pages <span class="badge bg-primary pull-right">11</span></a>
                            <ul>
                                <li><a href="calendar.html" data-original-title="Calendar"><i class="fa fa-calendar"></i><span class="hidden-minibar">Calendar</span></a></li>
                                <li><a href="chat.html" data-original-title="Chat"><i class="fa fa-comment"></i><span class="hidden-minibar">Chat</span></a></li>
                                <li><a href="profile.html" data-original-title="Profile Activity"><i class="fa fa-th"></i><span class="hidden-minibar">Profile Activity</span></a></li>

                                <li class="active"><a href="support.html" data-original-title="Support"><i class="fa fa-gears"></i><span class="hidden-minibar">Support</span></a></li>

                                <li><a href="typography.html" data-original-title="Typography"><i class="fa fa-text-width"></i><span class="hidden-minibar">Typography</span></a></li>
                            </ul>
                        </li>

                        <li><a href="icons.html" data-original-title="Icons"><i class="fa fa-truck"></i><span class="hidden-minibar">Icons</span></a></li>*@


                    </ul>
                </div>
            </div>
            <!-- /.left-sidebar -->

            <!-- .content -->
            <div class="content">

                <div class="row">
                    <div class="col-mod-12">

                        <ul class="breadcrumb">
                            @if (breadcrumb != null)
                            {
                                foreach (string item in breadcrumb)
                                {
                                <li>@Html.Raw(item)</li>
                                }
                            }
                        </ul>

                        <h3 class="page-header"><i class="@ViewBag.icon"></i>@ViewBag.h1<i class="fa fa-info-circle animated bounceInDown show-info"></i></h3>

                        <blockquote class="page-information hidden">
                            <p>
                                <b>@ViewBag.h1</b> @ViewBag.h2

                            </p>
                        </blockquote>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                    <!-- /row -->

                </div>
                <!-- /.content -->

                <!-- .right-sidebar -->

                <!-- /.right-sidebar-holder -->
            </div>
            <!-- /.right-sidebar -->
        </div>
        <!-- /.box-holder -->
    </div>
    <!-- /.site-holder -->



    <!-- Load JS here for Faster site load =============================-->
    @*<script src="https://code.angularjs.org/1.2.16/angular.min.js"></script>*@
    <script src="@Url.Content("~/js/jquery-1.10.2.min.js")"></script>
    <script src="@Url.Content("~/js/jquery-ui-1.10.3.custom.min.js")"></script>
    <script src="@Url.Content("~/js/less-1.5.0.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.ui.touch-punch.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-select.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-switch.js")"></script>
    <script src="@Url.Content("~/js/jquery.tagsinput.js")"></script>
    <script src="@Url.Content("~/js/jquery.placeholder.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-typeahead.js")"></script>
    <script src="@Url.Content("~/js/application.js")"></script>
    <script src="@Url.Content("~/js/moment.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.sortable.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/js/jquery.gritter.js")"></script>
    <script src="@Url.Content("~/js/jquery.nicescroll.min.js")"></script>
    <script src="@Url.Content("~/js/skylo.js")"></script>
    <script src="@Url.Content("~/js/prettify.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.noty.js")"></script>
    <script src="@Url.Content("~/js/bic_calendar.js")"></script>
    <script src="@Url.Content("~/js/jquery.accordion.js")"></script>
    @*    <script src="@Url.Content("~/js/theme-options.js")"></script>*@

    <script src="@Url.Content("~/js/bootstrap-progressbar.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-progressbar-custom.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-colorpicker.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap-colorpicker-custom.js")"></script>

    <script src="@Url.Content("~/js/bootstrap-datatables.js")"></script>
    <script src="@Url.Content("~/js/dataTables-custom.js")"></script>

    <!-- Core Jquery File  =============================-->
    <script src="@Url.Content("~/js/core.js")"></script>


</body>
</html>